### ISSUE TITLE
[BUG] The container stops the moment it starts

### ISSUE THREAD

**Issue by Restmon** [sgibson91/binderhub-deploy#154]
### Describe the bug
After I press on the 'triangle' button to start the container, the container stops the moment it starts. Eventually, it resulted in a state of 'Fail'. From the log file (json format), I can see that the container started. I even get a green notification that the container started. But in the same log, the container is killed the second it started. 

### To Reproduce
(fill in my specific App Id, App Key and Tenant Id)
Region: (Asia Pacific) Australia East
Binderhub Version: 0.2.0-n1011.hb49edf6
Aks Node Count: 2
Aks Node Vm Size: Standard_D2s_v3
Container Registry: dockerhub
(fill in my specific Docker Hub Username and Password)
Setup Docker Image: gibon91/binderhub-setup:1.3.0

### Expected behaviour
1. The state of the container is in 'Running' after pressing the 'triangle' start button
2. There is a blob resource under the resource group.

### Screenshots
[https://ibb.co/wCjr1rc](url)
[https://ibb.co/6HDTY29](url)
[https://ibb.co/YhMJW9F](url)
[https://ibb.co/P9WsJpd](url)

### Desktop (if relevant):
- Chrome, Windows

### Additional context
I chatted with the Azure support engineer. He thinks the reason is the restart policy is set to Never in the docker image.

**Comment by Restmon** [comment]
Hi sgibson91,

I noticed that the screenshot works if you copy-paste the url. Could you try again? If it still fails for you, I will try other options.

**Comment by sgibson91** [comment]
No sorry, the link is taking me to `https://github.com/sgibson91/binderhub-deploy/issues/url` which doesn't show anything other than an empty list of GitHub issues 😕

**Comment by Restmon** [comment]
I mean, paste the URL 'https://ibb.co/wCjr1rc' directly into the browser. It works for me.

**Comment by Restmon** [comment]
Here is the json message (id removed)

                                 "count": 1,
                                "firstTimestamp": "2022-09-05T11:51:20Z",
                                "lastTimestamp": "2022-09-05T11:51:20Z",
                                "name": "Started",
                                "message": "**Started container**",
                                "type": "Normal"
                            },
                            {
                                "count": 1,
                                "firstTimestamp": "2022-09-05T11:51:24Z",
                                "lastTimestamp": "2022-09-05T11:51:24Z",
                                "name": "Killing",
                                "message": "**Killing container with id <some id number>**",
                                "type": "Normal"
                            }
                        ]
                    },
                    "resources": {
                        "requests": {
                            "memoryInGB": 1.5,
                            "cpu": 1
                        }
                    }
                }
            }
        ],
        "initContainers": [],
        "restartPolicy": "Never",
        "osType": "Linux",
        "instanceView": {
            "events": [],
            "state": "**Failed**"

**Comment by sgibson91** [comment]
Hello,

I regret to inform you that I will be archiving this repository due to a lack of maintainership. I understand the impact this decision might have on the community of developers who rely on or contributed to the project, and I want to offer my deepest apologies for any inconvenience.

As you know, maintaining an open-source project requires a significant amount of time and effort. Unfortunately, I haven't been able to maintain the repository's quality to the level it deserves lately. Rather than letting it continue to stagnate, I have decided to archive it for the time being.

Once again, I apologise for any inconvenience this situation may cause.

Many thanks.
